---
  - name: "Deploy a web application"
    hosts: web_nodes
    become: yes
    roles:
      - python
      - web-app
# modifed to distrubuted arch
  - name: "Deploy a db application"
    hosts: db_nodes
    become: yes
    roles:
      - python
      - mysqldb