---
  - name: "Deploy a web application"
    hosts: localhost
    become: yes
    tasks: 
      - include: ./tasks/python_dep.yaml
      - include: ./tasks/mysqldb.yaml
      - include: ./tasks/web_flask.yaml